issues:
  # Number of days of inactivity before an issue becomes stale
  daysUntilStale: 0

  # Number of days of inactivity before a stale issue is closed
  daysUntilClose: 1

  # Issues with these labels will never be considered stale
  exemptLabels:
    - status:In-progress
    - status:Approved
    - status:Help-wanted

  # Label to use when marking an issue as stale
  staleLabel: stale

  # Comment to post when marking an issue as stale. Set to `false` to disable
  markComment: >
    This repository has been replaced by [virtual-environments](https://github.com/actions/virtual-environments) repository.
    If you have an issue or request for an image, please create an issue in the [virtual-environments](https://github.com/actions/virtual-environments) repository.
    This issue has been automatically marked as stale and will be closed.

  # Comment to post when closing a stale issue. Set to `false` to disable
  closeComment: false
